onedjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('specifies/<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Questions(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('published date')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Questions, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import Http404
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

from .models import Questions

from django.template import loader


def index(request):
    latest_question_list = Questions.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list':latest_question_list,
            }
    return HttpResponse(template.render(context, request))

def detail(request, question_id):
    try:
        question = Questions.objects.get(pk=question_id)
    except Questions.DoesNotExist:
        raise Http404('Question does not exists')
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    return HttpResponse("you're looking at the rsult of question %s."% question_id)

def vote(request, question_id):
    return HttpResponse("you're voting on question  %s."% question_id)

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{
˓→choice.id }}">
<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Questions</title>
    <link rel="stylesheet" href="{% static 'CSS/index.css' %}">
    
    </style>
</head>
<body>
    <div class="container">
        <ul class="nav">
            <li id="home" href="home.html">HOME</li>
            <li id="projects" href="projects.html">PROJETCS</li>
            <li id="about" href="about.html">ABOUT</li>
            <li id="contact" href="contact.html">CONTACT</li>
        </ul>
       <div class="question">
        {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
        <li class = "link"><a  href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
        {% else %}
        <p>No polls are available and there is no need for, fuck off.</p>
        {% endif %}
       </div>
    </div>



    
</body>
</html>